POST http://localhost:3000/exercicios
Content-Type: application/json

{
    "id": 0,
    "nome": "Supino reto",
    "grupo_muscular": "Peito",
    "quantidade_series": 4,
    "quantidade_repeticao": 10,
    "peso_carga": 20
}

###

PUT http://localhost:3000/exercicios/0
Content-Type: application/json

{
    "id": 0,
    "nome": "Supino reto",
    "grupo_muscular": "Peito",
    "quantidade_series": 4,
    "quantidade_repeticao": 5,
    "peso_carga": 5
}

###

DELETE http://localhost:3000/exercicios/0
Content-Type: application/json

###

GET http://localhost:3000/exercicios

###

POST http://localhost:3000/usuarios
Content-Type: application/json

{
    "id": 0,
    "nome": "Pedro",
    "email": "pedro.teste@gmail.com",
    "senha": "Teste@123456789"
}

###
PUT http://localhost:3000/usuarios/0
Content-Type: application/json

{
    "id": 0,
    "nome": "Pedro",
    "email": "pedro.teste@gmail.com",
    "senha": "sgdgdsbsdsddgs!5445342"
}

###

DELETE http:localhost:3000/usuarios/0
Content-Type: application/json
###
GET http://localhost:3000/usuarios
